grails:
    plugin:
        databasemigration:
            changelogFileName: 'changelog-transaction.groovy'
            changelogLocation: 'src/integration-test/resources'
            updateOnStart: false
            second:
                updateOnStart: false
---
server:
    port: 0
---
dataSources:
    dataSource:
        pooled: true
        jmxExport: true
        driverClassName: org.h2.Driver
        username: sa
        password:
        dbCreate: none
        url: jdbc:h2:mem:testDb
    other:
        pooled: true
        jmxExport: true
        driverClassName: org.h2.Driver
        username: sa
        password:
        dbCreate: none
        url: jdbc:h2:mem:otherDb
